databases:
  - name: agro-db
    plan: free

services:
  - type: web
    name: agro-inversiones-pos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agro_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    disk:
      name: media
      mountPath: /opt/render/project/src/media
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://agro-inversiones-pos.onrender.com,https://tu-dominio.com"
      - key: DJANGO_SETTINGS_MODULE
        value: agro_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: agro-db
          property: connectionString
    postDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python create_superuser.py
