databases:
  - name: AGRICOLA
    plan: free

services:
  - type: web
    name: agro-inversiones-pos
    env: python
    plan: free
    rootDirectory: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn agro_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /healthz
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://agricola-3r6y.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: agro_project.settings
      - key: APP_BASE_URL
        value: "https://agricola-3r6y.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: agro-db
          property: connectionString
    postDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python create_superuser.py
